# -*- coding: utf-8 -*-
"""mnist_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19xaCFyEPkyWo-G_qk6bq56xGCUHhHDwN
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

# ==========================================
# ۱. تنظیمات و آماده‌سازی داده‌ها
# ==========================================
# تبدیل تصاویر به بردار و نرمال‌سازی
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,)) # مقادیر استاندارد برای دیتاست MNIST
])

# دانلود داده‌های آموزش و تست
train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

# ایجاد لودرها برای دسته‌بندی داده‌ها
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size=64, shuffle=True)
test_loader = torch.utils.data.DataLoader(dataset=test_dataset, batch_size=64, shuffle=False)

# ==========================================
# ۲. تعریف ساختار شبکه عصبی (MLP)
# ==========================================
class MultiLayerPerceptron(nn.Module):
    def __init__(self):
        super(MultiLayerPerceptron, self).__init__()
        # لایه‌های شبکه
        self.fc1 = nn.Linear(28*28, 128) # لایه ورودی به پنهان اول
        self.fc2 = nn.Linear(128, 64)    # لایه پنهان اول به دوم
        self.fc3 = nn.Linear(64, 10)     # لایه خروجی (۱۰ عدد)
        self.dropout = nn.Dropout(0.2)   # برای جلوگیری از Overfitting

    def forward(self, x):
        # تخت کردن تصویر (تبدیل ماتریس ۲۸در۲۸ به یک خط ۷۸۴تایی)
        x = x.view(-1, 28*28)
        # عبور از لایه‌ها با تابع فعال‌سازی ReLU
        x = torch.relu(self.fc1(x))
        x = self.dropout(x)
        x = torch.relu(self.fc2(x))
        x = self.dropout(x)
        x = self.fc3(x) # لایه آخر معمولاً در PyTorch بدون Softmax است چون CrossEntropy آن را دارد
        return x

# ساخت شیء از مدل و انتقال به GPU در صورت وجود
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = MultiLayerPerceptron().to(device)

# ==========================================
# ۳. تعریف تابع خطا و بهینه‌ساز
# ==========================================
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# ==========================================
# ۴. حلقه آموزش (Training Loop)
# ==========================================
print("شروع فرآیند آموزش...")
epochs = 5
for epoch in range(epochs):
    model.train() # قرار دادن مدل در حالت آموزش
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in train_loader:
        # انتقال داده‌ها به دستگاه (CPU یا GPU)
        images, labels = images.to(device), labels.to(device)

        # ۱. صفر کردن گرادیان‌ها
        optimizer.zero_grad()

        # ۲. حدس مدل (Forward Pass)
        outputs = model(images)

        # ۳. محاسبه میزان خطا
        loss = criterion(outputs, labels)

        # ۴. محاسبه گرادیان‌ها (Backpropagation)
        loss.backward()

        # ۵. به‌روزرسانی وزن‌ها
        optimizer.step()

        # محاسبه دقت در لحظه
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
        running_loss += loss.item()

    # خروجی هر دور آموزش
    epoch_acc = 100 * correct / total
    print(f'Epoch [{epoch+1}/{epochs}] -> Loss: {running_loss/len(train_loader):.4f} | Accuracy: {epoch_acc:.2f}%')

# ==========================================
# ۵. ارزیابی نهایی روی داده‌های تست (امتحان نهایی)
# ==========================================
model.eval() # قرار دادن مدل در حالت ارزیابی
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print(f'\nدقت نهایی مدل روی داده‌های تست: {100 * correct / total:.2f}%')

# ==========================================
# ۶. نمایش یک نمونه پیش‌بینی بصری
# ==========================================
images, labels = next(iter(test_loader))
img = images[0]
with torch.no_grad():
    output = model(img.to(device))
    prediction = output.argmax().item()

plt.imshow(img.squeeze(), cmap='gray')
plt.title(f"Actual: {labels[0]} | Predicted: {prediction}")
plt.show()